# Generated by Django 5.2.1 on 2025-12-22 18:30

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="products/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="products/variants/",
                verbose_name="variant image",
            ),
        ),
    ]
