# Generated by Django 5.2.1 on 2025-12-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productimage_image_alter_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="aspect_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Height value used to compute aspect ratio (decimal allowed).",
                max_digits=8,
                null=True,
                verbose_name="aspect height",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="aspect_unit",
            field=models.CharField(
                choices=[
                    ("ratio", "Ratio (unitless)"),
                    ("in", "Inches"),
                    ("ft", "Feet"),
                    ("cm", "Centimeters"),
                    ("mm", "Millimeters"),
                    ("px", "Pixels"),
                ],
                default="ratio",
                max_length=10,
                verbose_name="aspect unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="aspect_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Width value used to compute aspect ratio (decimal allowed).",
                max_digits=8,
                null=True,
                verbose_name="aspect width",
            ),
        ),
    ]
