# Generated by Django 5.2.1 on 2025-12-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_aspect_height_category_aspect_unit_and_more"),
        ("products", "0003_product_aspect_height_product_aspect_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryProxy",
            fields=[],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("categories.category",),
        ),
    ]
