# Generated by Django 5.2.1 on 2025-12-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("products", "0004_categoryproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="currencies.currency",
                verbose_name="currency",
            ),
        ),
    ]
