# Generated by Django 5.2.1 on 2025-12-15 01:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., USD, EUR)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Currency name (e.g., US Dollar)", max_length=100
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., $, €)", max_length=10
                    ),
                ),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "symbol_position",
                    models.CharField(
                        choices=[
                            ("before", "Before amount"),
                            ("after", "After amount"),
                        ],
                        default="before",
                        max_length=10,
                    ),
                ),
                ("thousand_separator", models.CharField(default=",", max_length=5)),
                ("decimal_separator", models.CharField(default=".", max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_update_rates", models.BooleanField(default=True)),
                ("update_frequency_hours", models.PositiveIntegerField(default=24)),
                (
                    "exchange_rate_provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("openexchange", "Open Exchange Rates"),
                            ("fixer", "Fixer.io"),
                            ("ecb", "European Central Bank"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("show_currency_selector", models.BooleanField(default=True)),
                (
                    "show_original_price",
                    models.BooleanField(
                        default=False,
                        help_text="Show original price alongside converted price",
                    ),
                ),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("none", "No rounding"),
                            ("nearest_cent", "Nearest cent"),
                            ("nearest_99", "Nearest .99"),
                            ("nearest_95", "Nearest .95"),
                            ("nearest_integer", "Nearest whole number"),
                        ],
                        default="nearest_cent",
                        max_length=20,
                    ),
                ),
                ("last_rate_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency Settings",
                "verbose_name_plural": "Currency Settings",
            },
        ),
        migrations.CreateModel(
            name="UserCurrencyPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "auto_detect",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically detect currency from location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preferences",
                        to="currencies.currency",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Currency Preference",
                "verbose_name_plural": "User Currency Preferences",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Exchange rate",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "API"),
                            ("ecb", "European Central Bank"),
                            ("openexchange", "Open Exchange Rates"),
                            ("fixer", "Fixer.io"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="currencies.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-valid_from"],
                "unique_together": {("from_currency", "to_currency", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeRateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("date", models.DateField()),
                ("source", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_from",
                        to="currencies.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_to",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate History",
                "verbose_name_plural": "Exchange Rate History",
                "ordering": ["-date"],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
    ]
