# Generated by Django 5.2.1 on 2025-08-09 04:58

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the coupon (e.g., SUMMER20, FLAT100)",
                        max_length=50,
                        unique=True,
                        verbose_name="Coupon Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the coupon's purpose or offer.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                        default="fixed",
                        help_text="Choose whether the discount is a percentage or a fixed amount.",
                        max_length=10,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The value of the discount (e.g., 10 for 10% or 100 for ৳100 off).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Discount Value",
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The minimum total amount of the order required to use this coupon. Leave blank for no minimum.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Minimum Order Amount",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For percentage discounts, the maximum amount that can be discounted. Leave blank for no maximum.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Maximum Discount Amount",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time from which the coupon becomes active.",
                        verbose_name="Valid From",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time until which the coupon is valid. Leave blank for no expiry.",
                        null=True,
                        verbose_name="Valid Until",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this coupon can currently be used.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The maximum number of times this coupon can be used overall. Leave blank for unlimited.",
                        null=True,
                        verbose_name="Total Usage Limit",
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The maximum number of times a single user can use this coupon. Leave blank for unlimited.",
                        null=True,
                        verbose_name="Usage Limit Per User",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of times this coupon has been successfully used.",
                        verbose_name="Times Used",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "users_used",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who have successfully applied this coupon.",
                        related_name="used_coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users Who Used This Coupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="promotions__code_acae7b_idx"),
                    models.Index(
                        fields=["is_active", "valid_from", "valid_until"],
                        name="promotions__is_acti_c370cf_idx",
                    ),
                ],
            },
        ),
    ]
