# Generated by Django 5.2.1 on 2025-07-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_alter_coupon_options_remove_coupon_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="maximum_amount",
            new_name="max_discount_amount",
        ),
    ]
