# Generated by Django 5.2.1 on 2025-07-19 07:56

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_rename_maximum_amount_coupon_max_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Unique code for the coupon",
                max_length=50,
                unique=True,
                verbose_name="Coupon Code",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Discount Value",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Max Discount Amount",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_order_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Minimum Order Amount",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total Usage Limit"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit_per_user",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Usage Limit Per User"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Times Used"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Valid Until"
            ),
        ),
    ]
