# Generated by Django 5.2.1 on 2025-07-19 09:02

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0004_alter_coupon_code_alter_coupon_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="users_used",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have successfully applied this coupon.",
                related_name="used_coupons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users Who Used This Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                help_text="Unique code for the coupon (e.g., SUMMER20, FLAT100)",
                max_length=50,
                unique=True,
                verbose_name="Coupon Code",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the coupon's purpose or offer.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                default="fixed",
                help_text="Choose whether the discount is a percentage or a fixed amount.",
                max_length=10,
                verbose_name="Discount Type",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The value of the discount (e.g., 10 for 10% or 100 for ৳100 off).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Discount Value",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this coupon can currently be used.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For percentage discounts, the maximum amount that can be discounted. Leave blank for no maximum.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Maximum Discount Amount",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_order_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The minimum total amount of the order required to use this coupon. Leave blank for no minimum.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Minimum Order Amount",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The maximum number of times this coupon can be used overall. Leave blank for unlimited.",
                null=True,
                verbose_name="Total Usage Limit",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit_per_user",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The maximum number of times a single user can use this coupon. Leave blank for unlimited.",
                null=True,
                verbose_name="Usage Limit Per User",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of times this coupon has been successfully used.",
                verbose_name="Times Used",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time from which the coupon becomes active.",
                verbose_name="Valid From",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time until which the coupon is valid. Leave blank for no expiry.",
                null=True,
                verbose_name="Valid Until",
            ),
        ),
    ]
