# Generated by Django 5.2.1 on 2025-08-09 04:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique code like 'sslcommerz', 'bkash', 'stripe'",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=True, verbose_name="Is Online Method"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payment-icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "gateway_code",
                    models.CharField(
                        blank=True,
                        help_text="Code identifying the payment gateway (e.g., 'stripe', 'bkash', 'sslcommerz').",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        help_text="Gateway-specific configuration details (e.g., public key, secret key, webhook secret). Store securely.",
                        null=True,
                        verbose_name="Gateway Configuration (JSON)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        help_text="The ID of the associated order (e.g., from custom_order app).",
                        max_length=100,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                            ("processing", "Processing"),
                            ("requires_action", "Requires Customer Action"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BDT", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from payment gateway for the payment intent/session.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Payment Intent ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique transaction ID from payment gateway for the actual charge.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="Any other reference ID from the payment gateway.",
                        max_length=150,
                        null=True,
                        verbose_name="Gateway Reference",
                    ),
                ),
                (
                    "capture_status",
                    models.BooleanField(
                        default=False,
                        help_text="True if authorized funds have been captured.",
                        verbose_name="Is Captured",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if payment has been verified with the gateway.",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(default=False, verbose_name="Is Test Payment"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object containing error information from the payment gateway.",
                        null=True,
                        verbose_name="Error Details",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Arbitrary metadata from the payment gateway or for internal use.",
                        null=True,
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.paymentmethod",
                        verbose_name="Payment Method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique refund ID from payment gateway.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Refund ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Refund Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Reason for Refund"),
                ),
                (
                    "gateway_response_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON response from the payment gateway for the refund.",
                        null=True,
                        verbose_name="Gateway Response Data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g., 'charge.succeeded', 'payment_intent.succeeded', 'refund.created'",
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "gateway_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID of the event from the payment gateway.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Gateway Event ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Raw JSON payload received from the payment gateway webhook.",
                        verbose_name="Event Payload",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this event has been processed by the system.",
                        verbose_name="Processed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payments.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Event",
                "verbose_name_plural": "Payment Events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["gateway_event_id"],
                        name="payments_pa_gateway_5574b1_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="payments_pa_event_t_3e4d61_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_pa_created_4b9611_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order_id"], name="payments_pa_order_i_1d1c93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_b8a300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_intent_id"], name="payments_pa_payment_7ccbf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
            ),
        ),
    ]
