# Generated by Django 5.2.1 on 2025-07-13 05:18

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("order", "Order Inquiry"),
                            ("product", "Product Question"),
                            ("shipping", "Shipping Information"),
                            ("return", "Return/Exchange"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", django_ckeditor_5.fields.CKEditor5Field()),
                ("category", models.CharField(max_length=50)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["category", "-is_featured", "question"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("shipping", "🚚 Shipping Policy"),
                            ("returns", "🔄 Return Policy"),
                            ("privacy", "🔒 Privacy Policy"),
                            ("terms", "📜 Terms & Conditions"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("icon", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
