# Generated by Django 5.2.1 on 2025-07-24 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_alter_product_trending_product_brand"),
        ("wishlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time when the wishlist was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="wishlisted_by",
                to="products.product",
                verbose_name="Products",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when the wishlist was last updated.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
