# Generated by Django 5.2.1 on 2025-12-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_message",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_wrap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_wrap_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
    ]
