# Generated by Django 5.2.1 on 2025-12-29 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_gift_options"),
        ("promotions", "0002_alter_banner_image_alter_banner_image_mobile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_user_id_02a211_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the order was soft-deleted",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount amount applied",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Soft-delete flag; delete is logical",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("stripe", "Credit Card (Stripe)"), ("paypal", "PayPal")],
                db_index=True,
                default="stripe",
                help_text="Payment method used for this order",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Shipping"),
                    ("express", "Express Shipping"),
                    ("overnight", "Overnight Shipping"),
                ],
                db_index=True,
                default="standard",
                help_text="Shipping method chosen for this order",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, help_text="Order subtotal in BDT", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax amount applied",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, help_text="Order total in BDT", max_digits=10
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_orde_status_079368_idx"
            ),
        ),
    ]
