# Generated by Django 5.2.1 on 2025-12-15 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("base_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per_item_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order subtotal for free shipping",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("min_delivery_days", models.PositiveIntegerField(default=5)),
                ("max_delivery_days", models.PositiveIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Rate",
                "verbose_name_plural": "Shipping Rates",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("shipping_first_name", models.CharField(blank=True, max_length=100)),
                ("shipping_last_name", models.CharField(blank=True, max_length=100)),
                ("shipping_email", models.EmailField(blank=True, max_length=254)),
                ("shipping_phone", models.CharField(blank=True, max_length=20)),
                (
                    "shipping_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "shipping_country",
                    models.CharField(default="United States", max_length=100),
                ),
                ("billing_same_as_shipping", models.BooleanField(default=True)),
                ("billing_first_name", models.CharField(blank=True, max_length=100)),
                ("billing_last_name", models.CharField(blank=True, max_length=100)),
                (
                    "billing_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "billing_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "billing_country",
                    models.CharField(default="United States", max_length=100),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Shipping (5-7 days)"),
                            ("express", "Express Shipping (2-3 days)"),
                            ("overnight", "Overnight Shipping"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit Card (Stripe)"),
                            ("paypal", "PayPal"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_client_secret", models.CharField(blank=True, max_length=255)),
                ("order_notes", models.TextField(blank=True)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("cart", "Cart Review"),
                            ("shipping", "Shipping Information"),
                            ("payment", "Payment"),
                            ("review", "Review Order"),
                            ("complete", "Complete"),
                        ],
                        default="cart",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to="cart.cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout Session",
                "verbose_name_plural": "Checkout Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
