# Generated by Django 5.2.1 on 2025-12-17 17:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cart", "0002_initial"),
        ("checkout", "0001_initial"),
        ("orders", "0002_initial"),
        ("payments", "0001_initial"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("countries", models.JSONField(default=list)),
                ("regions", models.JSONField(blank=True, default=dict)),
                ("postal_patterns", models.JSONField(blank=True, default=list)),
                (
                    "surcharge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "surcharge_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percentage", "Percentage")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="Bangladesh", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                (
                    "pickup_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("min_pickup_time_hours", models.PositiveIntegerField(default=2)),
                ("max_hold_days", models.PositiveIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                ("accepts_pickup", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Location",
                "verbose_name_plural": "Store Locations",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="accept_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="billing_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="bkash_payment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="checkout_variant",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_sessions",
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="currency",
            field=models.CharField(default="BDT", max_length=3),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="delivery_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="device_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="fraud_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="fraud_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="gift_message",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="gift_wrap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="gift_wrap_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="information_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="information_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="nagad_payment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_session",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="order_placed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="payment_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="payment_setup_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="paypal_order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="referrer_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="review_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="saved_billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_billing_uses",
                to="accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="saved_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_uses",
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="saved_shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_shipping_uses",
                to="accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="security_token",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="shipping_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="shipping_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="shipping_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="shipping_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_sessions",
                to="checkout.shippingrate",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="subscribe_newsletter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="tax_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="utm_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="carrier",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="carrier_service",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="max_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum weight in kg",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="maximum_order_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum order amount for this shipping method",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="minimum_order_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum order amount for this shipping method",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="per_kg_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="billing_country",
            field=models.CharField(default="Bangladesh", max_length=100),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("cart", "Cart Review"),
                    ("information", "Customer Information"),
                    ("shipping", "Shipping Method"),
                    ("payment", "Payment"),
                    ("review", "Review Order"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("abandoned", "Abandoned"),
                    ("failed", "Failed"),
                ],
                default="cart",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Credit/Debit Card (Stripe)"),
                    ("paypal", "PayPal"),
                    ("cod", "Cash on Delivery"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="shipping_country",
            field=models.CharField(default="Bangladesh", max_length=100),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Shipping (5-7 days)"),
                    ("express", "Express Shipping (2-3 days)"),
                    ("overnight", "Overnight Shipping"),
                    ("pickup", "Store Pickup"),
                    ("free", "Free Shipping"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AbandonedCheckout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("cart_items", models.JSONField(default=list)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("abandoned_at_step", models.CharField(max_length=20)),
                ("abandoned_at", models.DateTimeField(auto_now_add=True)),
                ("recovery_emails_sent", models.PositiveIntegerField(default=0)),
                ("last_recovery_email_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_link", models.URLField(blank=True)),
                (
                    "recovery_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                ("is_recovered", models.BooleanField(default=False)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("is_contacted", models.BooleanField(default=False)),
                ("is_opted_out", models.BooleanField(default=False)),
                (
                    "checkout_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_record",
                        to="checkout.checkoutsession",
                    ),
                ),
                (
                    "recovered_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_source",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abandoned Checkout",
                "verbose_name_plural": "Abandoned Checkouts",
                "ordering": ["-abandoned_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("checkout_started", "Checkout Started"),
                            ("step_viewed", "Step Viewed"),
                            ("step_completed", "Step Completed"),
                            ("shipping_selected", "Shipping Selected"),
                            ("payment_selected", "Payment Selected"),
                            ("coupon_applied", "Coupon Applied"),
                            ("coupon_removed", "Coupon Removed"),
                            ("payment_started", "Payment Started"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("order_created", "Order Created"),
                            ("abandoned", "Abandoned"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("step", models.CharField(blank=True, max_length=20)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="checkout.checkoutsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout Event",
                "verbose_name_plural": "Checkout Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="shipping_zones",
            field=models.ManyToManyField(
                blank=True, related_name="shipping_rates", to="checkout.shippingzone"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_pickups",
                to="checkout.storelocation",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["user", "current_step"], name="checkout_ch_user_id_7bf942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["session_key", "current_step"],
                name="checkout_ch_session_dc8e79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(fields=["email"], name="checkout_ch_email_6ba5d5_idx"),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["created_at"], name="checkout_ch_created_c15d7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["current_step", "expires_at"],
                name="checkout_ch_current_41fbd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abandonedcheckout",
            index=models.Index(
                fields=["email", "-abandoned_at"], name="checkout_ab_email_1afc93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abandonedcheckout",
            index=models.Index(
                fields=["is_recovered", "-abandoned_at"],
                name="checkout_ab_is_reco_887abc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutevent",
            index=models.Index(
                fields=["checkout_session", "-created_at"],
                name="checkout_ch_checkou_acab64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="checkout_ch_event_t_2a5d5e_idx",
            ),
        ),
    ]
