# Generated by Django 5.2.1 on 2025-12-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_shippingzone_storelocation_and_more"),
        ("shipping", "0002_shippingzone_cities_alter_shippingzone_countries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="shipping_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_sessions",
                to="shipping.shippingrate",
            ),
        ),
    ]
