# Generated by Django 5.2.1 on 2025-12-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_update_shipping_rate_fk"),
        ("contacts", "0002_storelocation_max_hold_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_pickups",
                to="contacts.storelocation",
            ),
        ),
        migrations.DeleteModel(
            name="ShippingRate",
        ),
        migrations.DeleteModel(
            name="ShippingZone",
        ),
        migrations.DeleteModel(
            name="StoreLocation",
        ),
    ]
