# Generated by Django 5.2.1 on 2025-07-18 19:35

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default VAT Rate",
                        max_length=100,
                        unique=True,
                        verbose_name="Setting Name",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1000"),
                        help_text="VAT rate as a decimal (e.g., 0.10 for 10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Setting",
                "verbose_name_plural": "Tax Settings",
            },
        ),
    ]
