# Generated by Django 5.2.1 on 2025-08-09 04:58

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("confirm_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("shipping", "🚚 Shipping Policy"),
                            ("returns", "🔄 Return Policy"),
                            ("privacy", "🔒 Privacy Policy"),
                            ("terms", "📜 Terms & Conditions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=100)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="e.g. 'en' or 'bn'", max_length=10
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this version to users"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("icon", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="legal.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "ordering": ["policy_type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptances",
                        to="legal.policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_type", "is_active", "language"],
                name="legal_polic_policy__68cc67_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policy",
            unique_together={("policy_type", "version", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="policyacceptance",
            unique_together={("user", "policy", "version")},
        ),
    ]
