# Generated by Django 5.2.1 on 2025-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={
                "ordering": ["policy_type", "-version"],
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
            },
        ),
    ]
