# Generated by Django 5.2.1 on 2025-07-16 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_views",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(fields=["status"], name="analytics_o_status_d2c19f_idx"),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["timestamp"], name="analytics_o_timesta_1b7e80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["path"], name="analytics_p_path_3382b5_idx"),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["timestamp"], name="analytics_p_timesta_835321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["user"], name="analytics_p_user_id_23554e_idx"),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["product"], name="analytics_p_product_640e99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["timestamp"], name="analytics_p_timesta_878d8b_idx"
            ),
        ),
    ]
