# Generated by Django 5.2.1 on 2025-12-15 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="level"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, editable=False, max_length=1000, verbose_name="path"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="icon class"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="meta description"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="meta keywords"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.category",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="categories__slug_9b1a28_idx"),
                    models.Index(
                        fields=["parent"], name="categories__parent__91c7d9_idx"
                    ),
                    models.Index(fields=["level"], name="categories__level_f4d924_idx"),
                    models.Index(
                        fields=["is_active", "is_deleted"],
                        name="categories__is_acti_c77305_idx",
                    ),
                    models.Index(fields=["path"], name="categories__path_d816b7_idx"),
                ],
            },
        ),
    ]
