# Generated by Django 5.2.1 on 2025-12-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_aspect_height_category_aspect_unit_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="categories__level_f4d924_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
        migrations.AddField(
            model_name="category",
            name="depth",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="depth"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="categories.category",
                verbose_name="parent category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="path",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=1000,
                verbose_name="path",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=250, verbose_name="slug"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["depth"], name="categories__depth_448965_idx"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"), name="unique_parent_slug"
            ),
        ),
    ]
