# Generated by Django 5.2.1 on 2025-12-28 17:25

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_remove_category_categories__level_f4d924_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facet",
            fields=[
                (
                    "facet_code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=200)),
                ("data_type", models.CharField(max_length=20)),
                ("allowed_values", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Immutable category code (e.g., CAT_HOME)",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="external_mappings",
            field=models.JSONField(
                blank=True,
                help_text="Marketplace/Google mappings",
                null=True,
                verbose_name="external mappings",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="last_reviewed",
            field=models.DateField(blank=True, null=True, verbose_name="last reviewed"),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.CharField(blank=True, max_length=200, verbose_name="owner"),
        ),
        migrations.AddField(
            model_name="category",
            name="review_interval_days",
            field=models.PositiveIntegerField(
                default=90, verbose_name="review interval days"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="version"),
        ),
        migrations.AddField(
            model_name="category",
            name="visibility",
            field=models.CharField(
                default="published",
                help_text="draft/published/archived",
                max_length=20,
                verbose_name="visibility",
            ),
        ),
        migrations.CreateModel(
            name="ExternalCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("external_code", models.TextField()),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryAllowedFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.facet",
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "facet")},
            },
        ),
        migrations.CreateModel(
            name="ProductCategorySuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("confidence", models.FloatField(default=0.0)),
                ("method", models.CharField(default="heuristic", max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                (
                    "suggested_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product_id"], name="categories__product_ce0922_idx"
                    ),
                    models.Index(
                        fields=["suggested_category"],
                        name="categories__suggest_7e58a4_idx",
                    ),
                ],
            },
        ),
    ]
