# Generated by Django 5.2.1 on 2026-01-02 06:02

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storelocation",
            name="max_hold_days",
            field=models.PositiveIntegerField(
                default=7, help_text="Maximum days to hold for pickup"
            ),
        ),
        migrations.AddField(
            model_name="storelocation",
            name="min_pickup_time_hours",
            field=models.PositiveIntegerField(
                default=2, help_text="Minimum hours before pickup is ready"
            ),
        ),
        migrations.AddField(
            model_name="storelocation",
            name="pickup_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="contactattachment",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="contacts/attachments/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="storelocation",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="contacts/locations/",
            ),
        ),
    ]
