# Generated by Django 5.2.1 on 2025-12-25 03:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_storelocation_max_hold_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattachment",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="contacts/attachments/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="storelocation",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="contacts/locations/",
            ),
        ),
    ]
