# Generated by Django 5.2.1 on 2025-12-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_wrap_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable gift wrap option at checkout"
                    ),
                ),
                (
                    "gift_wrap_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee charged for gift wrapping (store currency)",
                        max_digits=10,
                    ),
                ),
                (
                    "gift_wrap_label",
                    models.CharField(
                        blank=True,
                        default="Gift Wrap",
                        help_text="Label to show for gift wrap option",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cart Settings",
                "verbose_name_plural": "Cart Settings",
            },
        ),
    ]
