# Generated by Django 5.2.1 on 2025-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartsettings",
            name="gift_wrap_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Fee charged for gift wrapping (store currency)",
                max_digits=10,
            ),
        ),
    ]
