# Generated by Django 5.2.1 on 2025-07-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="upazila",
            field=models.CharField(blank=True, max_length=100, verbose_name="upazila"),
        ),
    ]
