# Generated by Django 5.2.1 on 2025-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code, e.g., USD, EUR, BDT.",
                        max_length=3,
                        unique=True,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the currency, e.g., United States Dollar.",
                        max_length=50,
                        verbose_name="Currency Name",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol, e.g., $, €, ৳.",
                        max_length=5,
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Exchange rate against the base currency (e.g., BDT).",
                        max_digits=12,
                        verbose_name="Exchange Rate",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the default currency for the store?",
                        verbose_name="Default Currency",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this currency available for use?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["name"],
            },
        ),
    ]
