# Generated by Django 5.2.1 on 2025-12-17 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit/Debit Card (Stripe)"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("cod", "Cash on Delivery"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment-icons/"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for icon (e.g., 'card', 'bkash')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color theme: blue, pink, orange, green, gray",
                        max_length=20,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("none", "No Fee"),
                            ("flat", "Flat Fee"),
                            ("percent", "Percentage"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fee_text",
                    models.CharField(
                        blank=True,
                        help_text="Display text for fee (e.g., '৳20 fee')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "currencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supported currency codes. Empty means all currencies.",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supported country codes. Empty means all countries.",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("merchant_id", models.CharField(blank=True, max_length=100)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                (
                    "is_sandbox",
                    models.BooleanField(
                        default=True, help_text="Use sandbox/test mode"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions shown to customer after selecting this payment method",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_routing_number", models.CharField(blank=True, max_length=50)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
