# Generated by Django 5.2.1 on 2025-12-25 03:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentgateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="payment-icons/",
            ),
        ),
    ]
