# Generated by Django 5.2.1 on 2025-12-29 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_orders_orde_user_id_02a211_idx_and_more"),
        ("payments", "0003_alter_paymentgateway_icon"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgateway",
            name="bkash_app_key",
            field=models.CharField(
                blank=True, help_text="bKash app key (store securely)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bkash_app_secret",
            field=models.CharField(
                blank=True,
                help_text="bKash app secret (store securely)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bkash_mode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="bKash mode (sandbox/live)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bkash_password",
            field=models.CharField(
                blank=True, help_text="bKash API password or secret", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="bkash_username",
            field=models.CharField(
                blank=True, help_text="bKash API username", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="nagad_merchant_id",
            field=models.CharField(
                blank=True, help_text="Nagad merchant id", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="nagad_private_key",
            field=models.TextField(blank=True, help_text="Nagad private key (PEM)"),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="nagad_public_key",
            field=models.TextField(blank=True, help_text="Nagad public key (PEM)"),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="ssl_store_id",
            field=models.CharField(
                blank=True, help_text="SSLCommerz store id", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="ssl_store_passwd",
            field=models.CharField(
                blank=True,
                help_text="SSLCommerz store password (treat as secret)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="supports_bnpl",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Supports BNPL provider integration",
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="supports_partial",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Supports partial payments / splits",
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="supports_recurring",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Supports recurring payments/subscriptions",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="BDT",
                help_text="Primary currency is BDT (Bangladeshi Taka)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Public/publishable key where applicable (store secrets securely)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="api_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret key (store encrypted in production, e.g., a secrets manager)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="BNPLProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="payments_bn_code_fef684_idx"),
                    models.Index(
                        fields=["is_active"], name="payments_bn_is_acti_d180b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="payments_au_user_id_f2d761_idx"
                    ),
                    models.Index(
                        fields=["action"], name="payments_au_action_c5cf25_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_au_created_8e64cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BkashCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_key", models.CharField(blank=True, max_length=255)),
                ("app_secret", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("auth_token", models.CharField(blank=True, max_length=1024)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bkash_credentials",
                        to="payments.paymentgateway",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token_expires_at"],
                        name="payments_bk_token_e_953f9b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BNPLAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("approved", models.BooleanField(db_index=True, default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="payments.bnplprovider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="payments_bn_user_id_5a46eb_idx"
                    ),
                    models.Index(
                        fields=["provider_reference"],
                        name="payments_bn_provide_6d6f88_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated unique code",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Links",
                "indexes": [
                    models.Index(fields=["code"], name="payments_pa_code_e48d0c_idx"),
                    models.Index(
                        fields=["is_active"], name="payments_pa_is_acti_6c5616_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="payments_pa_expires_3a87cb_idx"
                    ),
                    models.Index(
                        fields=["order"], name="payments_pa_order_i_b50ce6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type reported by gateway (e.g., payment_success, refund)",
                        max_length=100,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gateway reference id (transaction id)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gateway", "-created_at"],
                        name="payments_pa_gateway_d63e0a_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="payments_pa_referen_72073c_idx"
                    ),
                    models.Index(
                        fields=["order"], name="payments_pa_order_i_d65105_idx"
                    ),
                    models.Index(
                        fields=["payment"], name="payments_pa_payment_0e8e31_idx"
                    ),
                ],
                "unique_together": {("gateway", "reference")},
            },
        ),
        migrations.CreateModel(
            name="RecurringCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("status", models.CharField(default="pending", max_length=30)),
                ("attempt_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional external subscription id reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_charges",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscription"], name="payments_re_subscri_5d4d65_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_re_status_50869a_idx"
                    ),
                    models.Index(
                        fields=["attempt_at"], name="payments_re_attempt_59d7d2_idx"
                    ),
                    models.Index(
                        fields=["payment"], name="payments_re_payment_cdd366_idx"
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="payments_re_stripe__df8c65_idx",
                    ),
                ],
            },
        ),
    ]
