# Generated by Django 5.2.1 on 2026-01-06 20:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_avatar"),
        ("catalog", "0002_attribute_attributevalue_badge_bundle_bundleitem_and_more"),
        ("contacts", "0002_storelocation_max_hold_days_and_more"),
        ("promotions", "0001_initial"),
        (
            "shipping",
            "0002_shippingzone_cities_alter_shipment_signature_image_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_wrap_enabled", models.BooleanField(default=False)),
                (
                    "gift_wrap_amount",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "gift_wrap_label",
                    models.CharField(blank=True, default="Gift Wrap", max_length=100),
                ),
                ("cart_expiry_days", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cart Settings",
                "verbose_name_plural": "Cart Settings",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_carts",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price_at_add",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("gift_wrap", models.BooleanField(default=False)),
                ("gift_message", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_cart_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_cart_items",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "security_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("shipping_first_name", models.CharField(blank=True, max_length=100)),
                ("shipping_last_name", models.CharField(blank=True, max_length=100)),
                ("shipping_company", models.CharField(blank=True, max_length=200)),
                ("shipping_email", models.EmailField(blank=True, max_length=254)),
                ("shipping_phone", models.CharField(blank=True, max_length=20)),
                (
                    "shipping_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "shipping_country",
                    models.CharField(default="Bangladesh", max_length=100),
                ),
                ("billing_same_as_shipping", models.BooleanField(default=True)),
                ("billing_first_name", models.CharField(blank=True, max_length=100)),
                ("billing_last_name", models.CharField(blank=True, max_length=100)),
                ("billing_company", models.CharField(blank=True, max_length=200)),
                (
                    "billing_address_line_1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "billing_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "billing_country",
                    models.CharField(default="Bangladesh", max_length=100),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Shipping (5-7 days)"),
                            ("express", "Express Shipping (2-3 days)"),
                            ("overnight", "Overnight Shipping"),
                            ("pickup", "Store Pickup"),
                            ("free", "Free Shipping"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit/Debit Card (Stripe)"),
                            ("paypal", "PayPal"),
                            ("cod", "Cash on Delivery"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="cod",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_client_secret", models.CharField(blank=True, max_length=255)),
                ("paypal_order_id", models.CharField(blank=True, max_length=255)),
                ("bkash_payment_id", models.CharField(blank=True, max_length=255)),
                ("nagad_payment_id", models.CharField(blank=True, max_length=255)),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_gift", models.BooleanField(default=False)),
                ("gift_message", models.TextField(blank=True, max_length=500)),
                ("gift_wrap", models.BooleanField(default=False)),
                (
                    "gift_wrap_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("order_notes", models.TextField(blank=True)),
                ("delivery_instructions", models.TextField(blank=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tax_included", models.BooleanField(default=False)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=10),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("cart", "Cart"),
                            ("information", "Information"),
                            ("shipping", "Shipping"),
                            ("payment", "Payment"),
                            ("review", "Review"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="cart",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to="commerce.cart",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_checkout_sessions",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_checkout_pickups",
                        to="contacts.storelocation",
                    ),
                ),
                (
                    "saved_billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_checkout_billing_uses",
                        to="accounts.address",
                    ),
                ),
                (
                    "saved_shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_checkout_shipping_uses",
                        to="accounts.address",
                    ),
                ),
                (
                    "shipping_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_checkout_sessions",
                        to="shipping.shippingrate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_checkout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Checkout Started"),
                            ("info_submitted", "Information Submitted"),
                            ("shipping_selected", "Shipping Selected"),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("order_created", "Order Created"),
                            ("abandoned", "Checkout Abandoned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="commerce.checkoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "price_at_add",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notify_on_sale", models.BooleanField(default=True)),
                ("notify_on_restock", models.BooleanField(default=True)),
                ("notify_on_price_drop", models.BooleanField(default=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_wishlist_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_wishlist_items",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.wishlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("share_token", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_view", models.BooleanField(default=True)),
                ("allow_purchase", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="commerce.wishlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="commerce_ca_user_id_00621f_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key"], name="commerce_ca_session_d85d16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["updated_at"], name="commerce_ca_updated_e95b75_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "variant")},
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["user", "current_step"], name="commerce_ch_user_id_051245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["session_key"], name="commerce_ch_session_638d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["expires_at"], name="commerce_ch_expires_1b0386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["current_step", "created_at"],
                name="commerce_ch_current_2b87ed_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "product", "variant")},
        ),
    ]
