# Generated by Django 5.2.1 on 2026-01-06 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_attribute_attributevalue_badge_bundle_bundleitem_and_more"),
        ("commerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionWishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_views", models.PositiveIntegerField(default=0)),
                (
                    "time_on_cart",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds spent on cart page"
                    ),
                ),
                ("checkout_attempts", models.PositiveIntegerField(default=0)),
                ("items_added", models.PositiveIntegerField(default=0)),
                ("items_removed", models.PositiveIntegerField(default=0)),
                ("items_saved_for_later", models.PositiveIntegerField(default=0)),
                ("quantity_changes", models.PositiveIntegerField(default=0)),
                ("coupons_tried", models.PositiveIntegerField(default=0)),
                ("coupons_applied", models.PositiveIntegerField(default=0)),
                ("coupons_failed", models.PositiveIntegerField(default=0)),
                ("first_source", models.CharField(blank=True, max_length=100)),
                ("last_source", models.CharField(blank=True, max_length=100)),
                ("first_item_added", models.DateTimeField(blank=True, null=True)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="commerce.cart",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cart Analytics",
            },
        ),
        migrations.CreateModel(
            name="SharedCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this shared cart",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("edit", "Can edit items"),
                            ("purchase", "Can purchase items"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        help_text="Optional password protection",
                        max_length=128,
                    ),
                ),
                (
                    "allowed_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed email addresses",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum number of uses", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="commerce.cart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shared_carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "emoji",
                    models.CharField(
                        blank=True, help_text="Emoji icon for collection", max_length=10
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="commerce.wishlist",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("wishlist", "name")},
            },
        ),
        migrations.CreateModel(
            name="AbandonedCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("cart_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("item_count", models.PositiveIntegerField()),
                ("items_snapshot", models.JSONField(default=list)),
                (
                    "recovery_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("recovery_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reminded", "Reminder Sent"),
                            ("recovered", "Recovered"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("next_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_discount_code", models.CharField(blank=True, max_length=50)),
                (
                    "recovery_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("abandoned_at", models.DateTimeField(auto_now_add=True)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("referrer", models.URLField(blank=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_tracking",
                        to="commerce.cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-abandoned_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_reminder_at"],
                        name="commerce_ab_status_95a541_idx",
                    ),
                    models.Index(
                        fields=["email", "status"], name="commerce_ab_email_aa5c3e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("converted_to_order", models.BooleanField(default=False)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="commerce.cart",
                    ),
                ),
                (
                    "cart_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="commerce.cartitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-reserved_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active", "expires_at"],
                        name="commerce_it_product_b9e495_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_active"],
                        name="commerce_it_expires_614b30_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="For guest alerts", max_length=254
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("any", "Any price drop"),
                            ("threshold", "When price drops below threshold"),
                            ("percentage", "When price drops by percentage"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "percentage_drop",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum percentage drop to alert",
                        null=True,
                    ),
                ),
                (
                    "price_at_creation",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "lowest_price_seen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_triggered", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="commerce_pr_product_d167a2_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="commerce_pr_user_id_1df2de_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedForLater",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_at_save", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notify_on_price_drop", models.BooleanField(default=True)),
                ("notify_on_restock", models.BooleanField(default=True)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_for_later_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_for_later_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "saved_at"],
                        name="commerce_sa_user_id_fdd9a3_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="commerce_sa_session_a6b76b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionWishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "price_at_add",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notify_on_sale", models.BooleanField(default=True)),
                ("notify_on_restock", models.BooleanField(default=True)),
                ("notify_on_price_drop", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.sessionwishlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("wishlist", "product", "variant")},
            },
        ),
        migrations.CreateModel(
            name="WishlistCollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.wishlistcollection",
                    ),
                ),
                (
                    "wishlist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="commerce.wishlistitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-added_at"],
                "unique_together": {("collection", "wishlist_item")},
            },
        ),
    ]
