# Generated by Django 5.2.1 on 2026-01-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_enhanced_commerce_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["priority", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sessionwishlistitem",
            options={"ordering": ["-priority", "-added_at"]},
        ),
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={"ordering": ["-priority", "-added_at"]},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="added_from",
            field=models.CharField(
                choices=[
                    ("product_page", "Product Page"),
                    ("category", "Category Page"),
                    ("search", "Search Results"),
                    ("wishlist", "Wishlist"),
                    ("recommendation", "Recommendation"),
                    ("quick_view", "Quick View"),
                    ("buy_again", "Buy Again"),
                    ("cart_drawer", "Cart Drawer"),
                    ("api", "API"),
                    ("other", "Other"),
                ],
                default="product_page",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="customer_note",
            field=models.TextField(
                blank=True, help_text="Customer notes for this item", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="gift_recipient_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="gift_recipient_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="internal_note",
            field=models.TextField(
                blank=True, help_text="Internal notes", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="locked_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price_locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Price lock expiry", null=True
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Item priority for display ordering"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="recurring_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 Weeks"),
                    ("monthly", "Monthly"),
                    ("bimonthly", "Every 2 Months"),
                    ("quarterly", "Quarterly"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="abandoned_cart_discount_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="abandoned_cart_discount_percent",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="abandoned_cart_max_reminders",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="abandoned_cart_reminder_delay_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="abandoned_cart_threshold_hours",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="default_currency",
            field=models.CharField(default="BDT", max_length=3),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="free_shipping_message",
            field=models.CharField(
                blank=True,
                default="Free delivery on orders over ৳2,000",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="free_shipping_threshold",
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="max_items_per_cart",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="max_quantity_per_item",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="minimum_order_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="minimum_order_message",
            field=models.CharField(
                blank=True, default="Minimum order amount not met", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="price_lock_auto_apply",
            field=models.BooleanField(
                default=False, help_text="Auto-apply price lock on add"
            ),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="price_lock_duration_hours",
            field=models.PositiveIntegerField(
                default=24, help_text="Default price lock duration"
            ),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="price_lock_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable price lock feature"
            ),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="stock_reservation_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartsettings",
            name="stock_reservation_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="sessionwishlistitem",
            name="desired_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sessionwishlistitem",
            name="lowest_price_seen",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="sessionwishlistitem",
            name="priority",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="sessionwishlistitem",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="desired_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="highest_price_seen",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="lowest_price_seen",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Low"), (2, "Normal"), (3, "High"), (4, "Must Have")],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="reminder_date",
            field=models.DateField(
                blank=True, help_text="When to remind about this item", null=True
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="reminder_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="target_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Notify when price drops to this",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Times product viewed from wishlist"
            ),
        ),
        migrations.AlterField(
            model_name="cartsettings",
            name="gift_wrap_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
