# Generated by Django 5.2.1 on 2025-07-21 09:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_alter_product_trending_product_brand"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewflag",
            options={
                "verbose_name": "Review Flag",
                "verbose_name_plural": "Review Flags",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewimage",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Review Image",
                "verbose_name_plural": "Review Images",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewvote",
            options={
                "verbose_name": "Review Vote",
                "verbose_name_plural": "Review Votes",
            },
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_product_99e47c_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_user_id_35ef9b_idx",
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alternative text for the image for accessibility.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the vote was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Detailed comment for the review (optional)."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the review was created.",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="flag_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this review has been flagged."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of 'helpful' votes for this review."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the user who submitted the review.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the review has been approved by a moderator.",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="not_helpful_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of 'not helpful' votes for this review."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pinned",
            field=models.BooleanField(
                default=False,
                help_text="Whether this review should be pinned to the top of review lists.",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                help_text="The product this review is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Rating given to the product (1 to 5 stars).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="sentiment_score",
            field=models.FloatField(
                blank=True,
                help_text="Sentiment score from external analysis (e.g., -1.0 to 1.0).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="source",
            field=models.CharField(
                choices=[
                    ("internal", "Internal Submission"),
                    ("google_reviews", "Google Reviews"),
                    ("third_party", "Third-Party Integration"),
                    ("filtered:keyword", "Filtered by Keyword"),
                    ("filtered:sentiment", "Filtered by Sentiment"),
                ],
                default="internal",
                help_text="Origin or reason for review status (e.g., 'internal', 'filtered:keyword').",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the review was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="The user who submitted this review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="User-Agent string from the client's request.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the review is from a verified buyer/source.",
            ),
        ),
        migrations.AlterField(
            model_name="reviewflag",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the review was flagged.",
            ),
        ),
        migrations.AlterField(
            model_name="reviewflag",
            name="reason",
            field=models.TextField(
                blank=True, help_text="Reason for flagging the review (optional)."
            ),
        ),
        migrations.AlterField(
            model_name="reviewflag",
            name="review",
            field=models.ForeignKey(
                help_text="The review being flagged.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="reviews.review",
            ),
        ),
        migrations.AlterField(
            model_name="reviewflag",
            name="user",
            field=models.ForeignKey(
                help_text="The user who flagged the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=models.ImageField(
                help_text="The image file for the review.",
                upload_to="review_images/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                help_text="The review this image belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reviews.review",
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="uploaded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the image was uploaded.",
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the vote was cast.",
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="is_helpful",
            field=models.BooleanField(
                default=True,
                help_text="True if the vote is 'helpful', False if 'not helpful'.",
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="review",
            field=models.ForeignKey(
                help_text="The review being voted on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="reviews.review",
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="user",
            field=models.ForeignKey(
                help_text="The user who cast the vote.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
