# Generated by Django 5.2.1 on 2025-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_options_alter_reviewflag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the review was created."
            ),
        ),
        migrations.AlterField(
            model_name="reviewflag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the review was flagged."
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the image was uploaded."
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the vote was cast."
            ),
        ),
    ]
