# Generated by Django 5.2.1 on 2026-01-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(default="analysis", max_length=100)),
                ("top_urls", models.JSONField(default=list)),
                ("suggested_headings", models.JSONField(default=list)),
                ("top_terms", models.JSONField(default=list)),
                ("recommended_word_count", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_briefs",
                        to="seo.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
