# Generated by Django 5.2.1 on 2025-12-25 03:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketattachment",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="support/attachments/%Y/%m/",
            ),
        ),
    ]
