# Generated by Django 5.2.1 on 2025-12-15 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Language code (e.g., en, fr, de)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name in English", max_length=100
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Language name in native language", max_length=100
                    ),
                ),
                (
                    "is_rtl",
                    models.BooleanField(
                        default=False, help_text="Right-to-left language"
                    ),
                ),
                (
                    "flag_code",
                    models.CharField(
                        blank=True,
                        help_text="Country code for flag icon",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "translation_progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Percentage of translations complete (0-100)",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="IANA timezone name", max_length=100, unique=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="User-friendly name", max_length=200),
                ),
                (
                    "offset",
                    models.CharField(
                        help_text="UTC offset (e.g., +05:30)", max_length=10
                    ),
                ),
                (
                    "offset_minutes",
                    models.IntegerField(
                        default=0, help_text="Offset in minutes for sorting"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_common",
                    models.BooleanField(
                        default=False, help_text="Show in common timezones list"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Timezone",
                "verbose_name_plural": "Timezones",
                "ordering": ["offset_minutes", "name"],
            },
        ),
        migrations.CreateModel(
            name="LocalizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("auto_detect_timezone", models.BooleanField(default=True)),
                ("show_language_selector", models.BooleanField(default=True)),
                ("show_timezone_selector", models.BooleanField(default=False)),
                ("enable_machine_translation", models.BooleanField(default=False)),
                (
                    "translation_api_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google Translate"),
                            ("deepl", "DeepL"),
                            ("azure", "Azure Translator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("translation_api_key", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="localization.language",
                    ),
                ),
                (
                    "default_timezone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="localization.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localization Settings",
                "verbose_name_plural": "Localization Settings",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code", max_length=2, unique=True
                    ),
                ),
                (
                    "code_alpha3",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 alpha-3 code", max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                ("default_currency_code", models.CharField(blank=True, max_length=3)),
                ("phone_code", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                ("continent", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_countries",
                        to="localization.language",
                    ),
                ),
                (
                    "default_timezone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_countries",
                        to="localization.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserLocalePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                            ("DD.MM.YYYY", "DD.MM.YYYY"),
                        ],
                        default="MM/DD/YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12-hour"), ("24h", "24-hour")],
                        default="12h",
                        max_length=10,
                    ),
                ),
                (
                    "measurement_system",
                    models.CharField(
                        choices=[("metric", "Metric"), ("imperial", "Imperial")],
                        default="metric",
                        max_length=10,
                    ),
                ),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("auto_detect_timezone", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="localization.country",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="localization.language",
                    ),
                ),
                (
                    "timezone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="localization.timezone",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locale_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Locale Preference",
                "verbose_name_plural": "User Locale Preferences",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("category", "Category"),
                            ("page", "Page"),
                            ("email", "Email Template"),
                            ("notification", "Notification"),
                            ("ui", "UI Element"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        help_text="ID of the content being translated", max_length=100
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name being translated", max_length=100
                    ),
                ),
                ("original_text", models.TextField(blank=True)),
                ("translated_text", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_machine_translated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="localization.language",
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "ordering": ["content_type", "content_id", "field_name"],
                "unique_together": {
                    ("content_type", "content_id", "field_name", "language")
                },
            },
        ),
    ]
