# Generated by Django 5.2.1 on 2025-12-17 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Division code (e.g., DHK for Dhaka)", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="localization.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "ordering": ["sort_order", "name"],
                "unique_together": {("country", "code")},
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="District code", max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                (
                    "shipping_zone",
                    models.CharField(
                        choices=[
                            ("metro", "Metro/City"),
                            ("suburban", "Suburban"),
                            ("rural", "Rural"),
                        ],
                        default="suburban",
                        help_text="Used for shipping rate calculation",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="localization.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["sort_order", "name"],
                "unique_together": {("division", "code")},
            },
        ),
        migrations.CreateModel(
            name="Upazila",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="Upazila code", max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                (
                    "upazila_type",
                    models.CharField(
                        choices=[
                            ("upazila", "Upazila"),
                            ("thana", "Thana"),
                            ("municipality", "Municipality"),
                            ("city_corporation", "City Corporation"),
                        ],
                        default="upazila",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_shipping_available", models.BooleanField(default=True)),
                (
                    "postal_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of postal codes for this upazila",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upazilas",
                        to="localization.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upazila",
                "verbose_name_plural": "Upazilas",
                "ordering": ["sort_order", "name"],
                "unique_together": {("district", "code")},
            },
        ),
    ]
