# Generated by Django 5.2.1 on 2025-12-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("localization", "0002_division_district_upazila"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocalepreference",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_locale_preferences",
                to="currencies.currency",
            ),
        ),
    ]
