# Generated by Django 5.2.1 on 2025-08-09 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_order", "0001_initial"),
        ("shipping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customorder",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
                verbose_name="Shipping Method",
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="customeritemimage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_item_images",
                to="custom_order.customorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="designimage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_images",
                to="custom_order.customorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="fabric_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.fabrictype",
                verbose_name="Fabric Type",
            ),
        ),
        migrations.AddField(
            model_name="orderstatusupdate",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_updates",
                to="custom_order.customorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="orderstatusupdate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="size_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.sizeoption",
                verbose_name="Size Option",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="custom_order.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="sizeoption",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave blank if applicable to all subcategories.",
                related_name="size_options",
                to="custom_order.subcategory",
                verbose_name="Applicable Subcategories",
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.subcategory",
                verbose_name="SubCategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "slug")},
        ),
    ]
