# Generated by Django 5.2.1 on 2025-07-17 14:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_useraddress_upazila"),
        ("custom_order", "0002_initial"),
        ("payments", "0001_initial"),
        ("promotions", "0001_initial"),
        ("shipping", "0002_alter_shippingmethod_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabrictype",
            name="available_colors",
        ),
        migrations.AddField(
            model_name="coloroption",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="colors/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="vat_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="VAT Percentage",
            ),
        ),
        migrations.AddField(
            model_name="sizeoption",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                related_name="size_options",
                to="custom_order.subcategory",
                verbose_name="Subcategories",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subcategories/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="coloroption",
            name="hex_code",
            field=models.CharField(
                blank=True,
                help_text="e.g., #FFFFFF",
                max_length=7,
                verbose_name="Hex Code",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="color_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.coloroption",
                verbose_name="Color Option",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("phone", "Phone Call"),
                    ("email", "Email"),
                    ("messenger", "Messenger"),
                ],
                default="whatsapp",
                max_length=20,
                verbose_name="Preferred Contact Method",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_orders",
                to="promotions.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="customer_item_condition",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Customer Item Condition"
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="fabric_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.fabrictype",
                verbose_name="Fabric Type",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="order_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Order ID",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("OWN_DESIGN", "Custom Design"),
                    ("SEND_PRODUCT", "Send Product for Customization"),
                    ("DIRECT_CONTACT", "Direct Contact for Consultation"),
                ],
                default="OWN_DESIGN",
                max_length=20,
                verbose_name="Order Type",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="payments.paymentmethod",
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="accounts.useraddress",
                verbose_name="Shipping Address",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="shipping.shippingmethod",
                verbose_name="Shipping Method",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="size_info",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Custom Size Information"
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="size_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.sizeoption",
                verbose_name="Size Option",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("ready", "Ready for Shipping"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.subcategory",
                verbose_name="Subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="designimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Is Primary Design"),
        ),
        migrations.AlterField(
            model_name="fabrictype",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Base Price",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="base_price_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Base Price Multiplier",
            ),
        ),
    ]
