# Generated by Django 5.2.1 on 2025-07-18 04:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_useraddress_upazila"),
        (
            "custom_order",
            "0003_remove_fabrictype_available_colors_coloroption_image_and_more",
        ),
        ("payments", "0002_paymentevent_refund_alter_payment_options_and_more"),
        ("promotions", "0002_alter_coupon_options_remove_coupon_active_and_more"),
        ("shipping", "0003_shipment_carrier_response_data_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
            },
        ),
        migrations.RemoveField(
            model_name="coloroption",
            name="image",
        ),
        migrations.AlterField(
            model_name="coloroption",
            name="hex_code",
            field=models.CharField(
                blank=True,
                help_text="Hexadecimal color code (e.g., #RRGGBB)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("messenger", "Messenger"),
                    ("phone", "Phone Call"),
                    ("email", "Email"),
                ],
                default="whatsapp",
                max_length=20,
                verbose_name="Preferred Contact Method",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotions.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("OWN_DESIGN", "Own Design"),
                    ("SEND_PRODUCT", "Send Product"),
                    ("DIRECT_CONTACT", "Direct Contact"),
                ],
                default="OWN_DESIGN",
                max_length=20,
                verbose_name="Order Type",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentmethod",
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.useraddress",
                verbose_name="Shipping Address",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
                verbose_name="Shipping Method",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="size_info",
            field=models.JSONField(
                blank=True,
                help_text="JSON object for detailed measurements (e.g., {'chest': 40, 'waist': 32})",
                null=True,
                verbose_name="Size Information",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("ready", "Ready for Shipment"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("on_hold", "On Hold"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_orders",
                to="custom_order.subcategory",
                verbose_name="SubCategory",
            ),
        ),
        migrations.AlterField(
            model_name="designimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Is Primary Image"),
        ),
        migrations.AlterField(
            model_name="fabrictype",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Base Price per Unit",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusupdate",
            name="old_status",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Old Status"
            ),
        ),
        migrations.AlterField(
            model_name="sizeoption",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave blank if applicable to all subcategories.",
                related_name="size_options",
                to="custom_order.subcategory",
                verbose_name="Applicable Subcategories",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="base_price_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Multiplier applied to fabric base price for this subcategory (e.g., 1.2 for complex designs).",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Base Price Multiplier",
            ),
        ),
    ]
