# Generated by Django 5.2.1 on 2025-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="cities",
            field=models.JSONField(
                default=list,
                help_text="List of city/district names (e.g., ['Dhaka', 'Mirpur', 'Gulshan'])",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="countries",
            field=models.JSONField(
                default=list,
                help_text="List of ISO country codes (e.g., ['US', 'BD', 'GB'])",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="postal_codes",
            field=models.JSONField(
                default=list,
                help_text="List of postal code patterns (e.g., ['1200', '1205', '56*'])",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="states",
            field=models.JSONField(
                default=list,
                help_text="List of state/division names (e.g., ['Dhaka', 'Rangpur'])",
            ),
        ),
    ]
