# Generated by Django 5.2.1 on 2026-01-02 06:02

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0002_contenttranslation_country_currency_district_and_more"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="cities",
            field=models.JSONField(
                default=list,
                help_text="List of city/district names (e.g., ['Dhaka', 'Mirpur', 'Gulshan'])",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="signatures/",
            ),
        ),
        migrations.AlterField(
            model_name="shippingcarrier",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="carriers/",
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_rates",
                to="i18n.currency",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="countries",
            field=models.JSONField(
                default=list,
                help_text="List of ISO country codes (e.g., ['US', 'BD', 'GB'])",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="postal_codes",
            field=models.JSONField(
                default=list,
                help_text="List of postal code patterns (e.g., ['1200', '1205', '56*'])",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="states",
            field=models.JSONField(
                default=list,
                help_text="List of state/division names (e.g., ['Dhaka', 'Rangpur'])",
            ),
        ),
    ]
