# Generated by Django 5.2.1 on 2025-12-25 03:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_shippingzone_cities_alter_shippingzone_countries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="signatures/",
            ),
        ),
        migrations.AlterField(
            model_name="shippingcarrier",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="carriers/",
            ),
        ),
    ]
