# Generated by Django 5.2.1 on 2025-12-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("shipping", "0003_alter_shipment_signature_image_and_more"),
    ]

    def _create_currency_rows(apps, schema_editor):
        Currency = apps.get_model('currencies', 'Currency')
        ShippingRate = apps.get_model('shipping', 'ShippingRate')
        from django.db import connection

        with connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT currency FROM shipping_shippingrate")
            rows = cursor.fetchall()
        codes = [r[0] for r in rows if r and r[0]]

        for code in codes:
            # Skip values that are already UUIDs (possible early runs)
            try:
                import uuid as _uuid
                _uuid.UUID(code)
                continue
            except Exception:
                pass

            if not Currency.objects.filter(code=code).exists():
                Currency.objects.create(code=code, name=code, symbol=code)

    def _populate_temp_currency_field(apps, schema_editor):
        Currency = apps.get_model('currencies', 'Currency')
        ShippingRate = apps.get_model('shipping', 'ShippingRate')

        # For each ShippingRate, if its current currency value (text) matches a Currency.code, set currency_temp accordingly
        for sr in ShippingRate.objects.all():
            code = getattr(sr, 'currency', None)
            if not code:
                continue
            try:
                # If it's already a UUID or FK, skip
                import uuid as _uuid
                _uuid.UUID(str(code))
                # If this succeeded, we assume it's already a PK and skip
                continue
            except Exception:
                pass

            cur = Currency.objects.filter(code=code).first()
            if cur:
                sr.currency_temp = cur
                sr.save(update_fields=['currency_temp'])

    def _noop_reverse(apps, schema_editor):
        # No-op reverse for data migration
        pass

    operations = [
        migrations.RunPython(_create_currency_rows, _noop_reverse),
        migrations.AddField(
            model_name='shippingrate',
            name='currency_temp',
            field=models.ForeignKey(
                to='currencies.currency',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
            ),
        ),
        migrations.RunPython(_populate_temp_currency_field, _noop_reverse),
        migrations.RemoveField(
            model_name='shippingrate',
            name='currency',
        ),
        migrations.RenameField(
            model_name='shippingrate',
            old_name='currency_temp',
            new_name='currency',
        ),
    ]
