# Generated by Django 5.2.1 on 2025-12-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0001_initial"),
        ("shipping", "0004_alter_shippingrate_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingrate",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_rates",
                to="i18n.currency",
            ),
        ),
    ]
