# Generated by Django 5.2.1 on 2025-12-25 03:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="pages/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
    ]
