# Generated by Django 5.2.1 on 2026-01-02 06:02

import apps.pages.models
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="free_shipping_threshold",
        ),
        migrations.AlterField(
            model_name="page",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="pages/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="currency",
            field=models.CharField(default="BDT", max_length=3),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="currency_symbol",
            field=models.CharField(default="৳", max_length=5),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an image or SVG (preferred).",
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="site/social/",
                        validators=[apps.pages.models.SocialLink.validate_icon_file],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="pages.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order"],
            },
        ),
    ]
