# Generated by Django 5.2.1 on 2025-12-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_sociallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="pages.sitesettings",
            ),
        ),
    ]
