# Generated by Django 5.2.1 on 2025-12-25 05:11

import apps.pages.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_sociallink_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="icon_svg",
            field=models.FileField(
                blank=True,
                help_text="Upload an .svg file to use as the social icon (preferred).",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/social/",
                validators=[apps.pages.models.validate_svg_file],
            ),
        ),
    ]
