# Generated by Django 5.2.1 on 2025-12-25 05:24

import apps.pages.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_sociallink_icon_svg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="icon_svg",
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Upload an image or SVG (preferred).",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="site/social/",
                validators=[apps.pages.models.SocialLink.validate_icon_file],
            ),
        ),
    ]
