# Generated by Django 5.2.1 on 2025-12-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_remove_gift_wrap_and_free_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="currency",
            field=models.CharField(default="BDT", max_length=3),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="currency_symbol",
            field=models.CharField(default="৳", max_length=5),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
