# Generated by Django 5.2.1 on 2025-08-09 04:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "saved_for_later",
                    models.BooleanField(
                        default=False,
                        help_text="If true, item is saved for later, not part of active cart total.",
                        verbose_name="Saved for Later",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Added At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "ordering": ["added_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Used for anonymous carts.",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "checked_out",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the cart has been converted to an order.",
                        verbose_name="Checked Out",
                    ),
                ),
                (
                    "abandoned",
                    models.BooleanField(
                        default=False,
                        help_text="True if the cart has been flagged as abandoned.",
                        verbose_name="Abandoned",
                    ),
                ),
                (
                    "abandoned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the cart was marked as abandoned.",
                        null=True,
                        verbose_name="Abandoned At",
                    ),
                ),
                (
                    "converted",
                    models.BooleanField(
                        default=False,
                        help_text="True if the cart led to a successful conversion (e.g., order placed).",
                        verbose_name="Converted",
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the cart was converted.",
                        null=True,
                        verbose_name="Converted At",
                    ),
                ),
                (
                    "is_express",
                    models.BooleanField(
                        default=False,
                        help_text="Whether express shipping is selected for this cart.",
                        verbose_name="Express Shipping",
                    ),
                ),
                (
                    "total_price_cached",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total Price (Cached)",
                    ),
                ),
                (
                    "total_discount_cached",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total Discount (Cached)",
                    ),
                ),
                (
                    "total_shipping_cached",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total Shipping (Cached)",
                    ),
                ),
                (
                    "total_tax_cached",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total Tax (Cached)",
                    ),
                ),
                (
                    "final_total_cached",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Final Total (Cached)",
                    ),
                ),
                (
                    "total_items_cached",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Items (Cached)"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.useraddress",
                        verbose_name="Shipping Address",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts_applied",
                        to="promotions.coupon",
                        verbose_name="Coupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "ordering": ["-created_at"],
            },
        ),
    ]
