# Generated by Django 5.2.1 on 2025-07-18 04:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0001_initial"),
        ("promotions", "0002_alter_coupon_options_remove_coupon_active_and_more"),
        ("shipping", "0003_shipment_carrier_response_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-saved_for_later", "added_at"],
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.AlterModelOptions(
            name="taxconfiguration",
            options={
                "verbose_name": "Tax Configuration",
                "verbose_name_plural": "Tax Configuration",
            },
        ),
        migrations.RemoveField(
            model_name="cart",
            name="is_express",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="shipping_carrier",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="shipping_zone",
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="shipping.shippingmethod",
                verbose_name="Shipping Method",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="abandoned",
            field=models.BooleanField(
                default=False,
                help_text="True if the cart was abandoned.",
                verbose_name="Abandoned",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="abandoned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Abandoned At"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="checked_out",
            field=models.BooleanField(
                default=False,
                help_text="True if the cart has been converted to an order.",
                verbose_name="Checked Out",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="converted",
            field=models.BooleanField(
                default=False,
                help_text="True if the cart led to a successful order.",
                verbose_name="Converted",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Converted At"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="promotions.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Used for anonymous carts.",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Added At"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="saved_for_later",
            field=models.BooleanField(
                default=False,
                help_text="True if the item is saved for later, not in active cart.",
                verbose_name="Saved for Later",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="taxconfiguration",
            name="default_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="The default tax rate applied to carts, in percentage.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Default Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="taxconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["abandoned", "abandoned_at"],
                name="cart_cart_abandon_9dfd4c_idx",
            ),
        ),
    ]
