# Generated by Django 5.2.1 on 2025-07-20 12:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_options_alter_cartitem_options_and_more"),
        ("products", "0001_initial"),
        ("promotions", "0005_coupon_users_used_alter_coupon_code_and_more"),
        ("shipping", "0003_shipment_carrier_response_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ("added_at",),
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_user_id_c464b8_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_session_ee6652_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_abandon_9dfd4c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cart",
            name="is_express",
            field=models.BooleanField(default=False, verbose_name="Express Shipping"),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Price at time of addition",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="abandoned",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the cart has been abandoned.",
                verbose_name="Abandoned",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="abandoned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the cart was marked as abandoned.",
                null=True,
                verbose_name="Abandoned At",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="checked_out",
            field=models.BooleanField(default=False, verbose_name="Checked Out"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="converted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the abandoned cart was converted to an order.",
                verbose_name="Converted",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="converted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the abandoned cart was converted.",
                null=True,
                verbose_name="Converted At",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotions.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
                verbose_name="Shipping Method",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Added At"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="saved_for_later",
            field=models.BooleanField(
                default=False,
                help_text="If true, item is saved for later, not in active cart.",
                verbose_name="Saved for Later",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key"], name="cart_cart_session_5e1af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="cart_cart_user_id_b645f9_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["checked_out"], name="cart_cart_checked_68b980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["abandoned"], name="cart_cart_abandon_7e9814_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="cart_cartit_cart_id_4bd8c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "saved_for_later"],
                name="cart_cartit_cart_id_dabe0c_idx",
            ),
        ),
    ]
