# Generated by Django 5.2.1 on 2025-07-20 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_options_alter_cartitem_options_and_more"),
        ("products", "0001_initial"),
        ("promotions", "0005_coupon_users_used_alter_coupon_code_and_more"),
        ("shipping", "0003_shipment_carrier_response_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["added_at"],
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_user_id_b645f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_checked_68b980_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_abandon_7e9814_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cart_cartit_cart_id_4bd8c3_idx",
        ),
        migrations.AlterField(
            model_name="cart",
            name="abandoned",
            field=models.BooleanField(
                default=False,
                help_text="True if the cart has been flagged as abandoned.",
                verbose_name="Abandoned",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="checked_out",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the cart has been converted to an order.",
                verbose_name="Checked Out",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="converted",
            field=models.BooleanField(
                default=False,
                help_text="True if the cart led to a successful conversion (e.g., order placed).",
                verbose_name="Converted",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="converted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the cart was converted.",
                null=True,
                verbose_name="Converted At",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts_applied",
                to="promotions.coupon",
                verbose_name="Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="is_express",
            field=models.BooleanField(
                default=False,
                help_text="Whether express shipping is selected for this cart.",
                verbose_name="Express Shipping",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Added At"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="saved_for_later",
            field=models.BooleanField(
                default=False,
                help_text="If true, item is saved for later, not part of active cart total.",
                verbose_name="Saved for Later",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["user", "checked_out"], name="cart_cart_user_id_c464b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["abandoned", "abandoned_at"],
                name="cart_cart_abandon_9dfd4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="cart_cartit_product_985dba_idx"
            ),
        ),
    ]
