# Generated by Django 5.2.1 on 2025-07-20 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="final_total_cached",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Final Total (Cached)",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_discount_cached",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Total Discount (Cached)",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_items_cached",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Items (Cached)"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_price_cached",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Total Price (Cached)",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_shipping_cached",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Total Shipping (Cached)",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_tax_cached",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Total Tax (Cached)",
            ),
        ),
    ]
