# Generated by Django 5.2.1 on 2025-07-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_seller"),
        ("cart", "0005_cart_final_total_cached_cart_total_discount_cached_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.useraddress",
                verbose_name="Shipping Address",
            ),
        ),
    ]
