# Generated by Django 5.2.1 on 2025-07-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaxConfiguration",
        ),
    ]
