# Generated by Django 5.2.1 on 2025-12-15 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Placeholder to ensure app is initialized
        migrations.CreateModel(
            name='_CatalogPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={'managed': False},
        ),
    ]
