# Generated by Django 5.2.1 on 2025-08-09 04:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Carrier Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Unique code for API integration or internal reference",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Carrier Code",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for the carrier's API (e.g., https://api.carrier.com/v1)",
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("API_KEY", "API Key"),
                            ("OAUTH2", "OAuth 2.0"),
                            ("BASIC", "Basic Auth"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="Authentication Type",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for integration with carrier's system (if API_KEY auth)",
                        max_length=255,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "credentials_json",
                    models.JSONField(
                        blank=True,
                        help_text="Additional API credentials in JSON format (e.g., {'client_id': '...', 'client_secret': '...'}). Store securely.",
                        null=True,
                        verbose_name="API Credentials (JSON)",
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(
                        blank=True,
                        help_text="URL template for tracking shipments (e.g., https://carrier.com/track/{tracking_number})",
                        verbose_name="Tracking URL Template",
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret key for verifying incoming webhooks from this carrier.",
                        max_length=255,
                        verbose_name="Webhook Secret",
                    ),
                ),
                (
                    "return_api_url",
                    models.URLField(
                        blank=True,
                        help_text="API endpoint for initiating returns with this carrier.",
                        verbose_name="Return API URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Shipping Carrier",
                "verbose_name_plural": "Shipping Carriers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "tracking_url_generated",
                    models.URLField(
                        blank=True,
                        help_text="The actual tracking URL generated by the carrier's API.",
                        verbose_name="Generated Tracking URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("BOOKED", "Booked"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out For Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                            ("RETURNED", "Returned"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Cost",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "dims_cm",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object: {'l': length, 'w': width, 'h': height}",
                        null=True,
                        verbose_name="Dimensions (cm)",
                    ),
                ),
                (
                    "carrier_response_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON response from the carrier's API for booking/tracking.",
                        null=True,
                        verbose_name="Carrier API Response Data",
                    ),
                ),
                (
                    "delivery_proof_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to image/document proving delivery.",
                        verbose_name="Delivery Proof URL",
                    ),
                ),
                (
                    "delivery_signature_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to image of recipient's signature.",
                        verbose_name="Delivery Signature URL",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="custom_order.customorder",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g., 'SCAN', 'EXCEPTION', 'DELIVERY_ATTEMPT'",
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Location"
                    ),
                ),
                (
                    "event_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Event Timestamp",
                    ),
                ),
                (
                    "carrier_raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON data from the carrier's webhook/API for this event.",
                        null=True,
                        verbose_name="Carrier Raw Event Data",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shipment",
                        verbose_name="Shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Event",
                "verbose_name_plural": "Shipment Events",
                "ordering": ["-event_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Old Status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("BOOKED", "Booked"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out For Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=20,
                        verbose_name="New Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="shipping.shipment",
                        verbose_name="Shipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Status Update",
                "verbose_name_plural": "Shipment Status Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Method Name")),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price per KG",
                    ),
                ),
                (
                    "base_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed charge for this method, added to weight-based cost",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Base Charge",
                    ),
                ),
                (
                    "estimated_delivery_days",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '3-5 business days', 'Next day'",
                        max_length=50,
                        verbose_name="Estimated Delivery Days",
                    ),
                ),
                (
                    "guaranteed_delivery_days",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2 business days' for guaranteed delivery services",
                        max_length=50,
                        verbose_name="Guaranteed Delivery Days",
                    ),
                ),
                (
                    "is_express",
                    models.BooleanField(default=False, verbose_name="Is Express"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "min_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum weight for this shipping method",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Minimum Weight (kg)",
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum weight for this shipping method",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Maximum Weight (kg)",
                    ),
                ),
                (
                    "min_dims_cm",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object: {'l': length, 'w': width, 'h': height}. Min dimensions for this method.",
                        null=True,
                        verbose_name="Minimum Dimensions (cm)",
                    ),
                ),
                (
                    "max_dims_cm",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object: {'l': length, 'w': width, 'h': height}. Max dimensions for this method.",
                        null=True,
                        verbose_name="Maximum Dimensions (cm)",
                    ),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="Carrier-specific code for this service (e.g., 'PRIORITY_OVERNIGHT')",
                        max_length=100,
                        verbose_name="Carrier Service Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_methods",
                        to="shipping.shippingcarrier",
                        verbose_name="Carrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="shipping.shippingmethod",
                verbose_name="Shipping Method",
            ),
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Zone Name"
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Base Cost",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Order total above which shipping is free (0 for no free shipping)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Free Shipping Threshold",
                    ),
                ),
                (
                    "volumetric_divisor",
                    models.PositiveIntegerField(
                        default=5000,
                        help_text="Divisor for calculating volumetric weight (L*W*H / Divisor)",
                        verbose_name="Volumetric Divisor",
                    ),
                ),
                (
                    "postal_codes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of postal codes or ranges (e.g., ['1200', '1205-1210'])",
                        null=True,
                        verbose_name="Applicable Postal Codes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        related_name="shipping_zones",
                        to="shipping.region",
                        verbose_name="Regions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="zones",
            field=models.ManyToManyField(
                help_text="The shipping zones where this method is available.",
                related_name="shipping_methods",
                to="shipping.shippingzone",
                verbose_name="Applicable Zones",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shippingmethod",
            unique_together={("name", "carrier")},
        ),
    ]
