# Generated by Django 5.2.1 on 2025-07-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shippingmethod",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="zones",
            field=models.ManyToManyField(
                related_name="shipping_methods",
                to="shipping.shippingzone",
                verbose_name="Zones",
            ),
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="zone",
        ),
    ]
