# Generated by Django 5.2.1 on 2025-07-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_shipping_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
    ]
