# Generated by Django 5.2.1 on 2025-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price per unit at the time of order",
                max_digits=10,
            ),
        ),
    ]
