# Generated by Django 5.2.1 on 2025-12-15 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist",
                "verbose_name_plural": "Wishlists",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this item"
                    ),
                ),
                (
                    "price_at_add",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price when item was added",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notify_on_sale",
                    models.BooleanField(
                        default=True, help_text="Notify when item goes on sale"
                    ),
                ),
                (
                    "notify_on_restock",
                    models.BooleanField(
                        default=True, help_text="Notify when item is back in stock"
                    ),
                ),
                (
                    "notify_on_price_drop",
                    models.BooleanField(default=True, help_text="Notify on price drop"),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wishlist_items",
                        to="products.productvariant",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wishlist.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
                "ordering": ["-added_at"],
                "unique_together": {("wishlist", "product", "variant")},
            },
        ),
        migrations.CreateModel(
            name="WishlistNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("price_drop", "Price Drop"),
                            ("back_in_stock", "Back in Stock"),
                            ("sale", "On Sale"),
                            ("low_stock", "Low Stock Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wishlist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="wishlist.wishlistitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Notification",
                "verbose_name_plural": "Wishlist Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("share_token", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_view", models.BooleanField(default=True)),
                (
                    "allow_purchase",
                    models.BooleanField(
                        default=False, help_text="Allow others to buy items"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="wishlist.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Share",
                "verbose_name_plural": "Wishlist Shares",
                "ordering": ["-created_at"],
            },
        ),
    ]
